version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: pdm_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pdm
  api:
    build:
      context: ./api
    container_name: pdm_api
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=pdm
      - MONGO_COLL=sensor_data
    volumes:
      - ./api/app:/app/app
volumes:
  mongo_data:
